In [1]:
import pandas as pd

In [2]:
dados = pd.read_csv('https://raw.githubusercontent.com/LuizinhoXT/Python/refs/heads/main/machine_learning/nlp_machine_learning/dataset_avaliacoes.csv')

In [4]:
dados.head()

,ID_avaliacao,avaliacao,nota,sentimento
0,81841,"Esse smartphone superou minhas expectativas, r...",5,positivo
1,28031,o cheiro e muito desagradavel!! pra quem se in...,2,negativo
2,91332,"Eu fiz a compra a loja não entregou o produto,...",1,negativo
3,110045,"Atendeu minhas expectativas, só achei a luz ru...",4,positivo
4,36929,"Gostei muito, só achei que ficou a desejar a q...",5,positivo

In [5]:
dados.value_counts('sentimento')

sentimento
positivo    7890
negativo    7611
Name: count, dtype: int64

In [9]:
print('positivo \n\n', dados.avaliacao[0])

positivo

 Esse smartphone superou minhas expectativas, recomendo

In [12]:
print('negativo \n\n', dados.avaliacao[1])

negativo

 o cheiro e muito desagradavel!! pra quem se incomoda  nao recomendoo..

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
# teste de vetorização para entender o funcionamento do algoritimo

texto = ['Esse smartphone superou minhas expectativas, recomendo', 'o cheiro e muito desagradavel!! pra quem se incomoda  nao recomendoo..']

vetorizar = CountVectorizer()
bag_of_words = vetorizar.fit_transform(texto)

In [22]:
# Matrix esparsa é o retorno de bag_of_words que acontece quando temos vários 0's dentro de uma matriz
bag_of_words

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 15 stored elements and shape (2, 15)>

In [ ]:
# Através da vetorização, criamos uma tabela em que os elementos escalam de maneira horizontal, gerando assim uma classificação binária que avalia se determinada palavra existe ou não exister em determinado registro de dados.

matriz_esparsa = pd.DataFrame.sparse.from_spmatrix(bag_of_words,columns=vetorizar.get_feature_names_out())

matriz_esparsa

,cheiro,desagradavel,esse,expectativas,incomoda,minhas,muito,nao,pra,quem,recomendo,recomendoo,se,smartphone,superou
0,0,0,1,1,0,1,0,0,0,0,1,0,0,1,1
1,1,1,0,0,1,0,1,1,1,1,0,1,1,0,0

In [ ]:
# A dimensão na pós vetorização aumenta horizontalmente e isso se mostra no Output dessa célula com +23k de colunas.
# Isso é um problema pois é computacionalmente caro

vetorizar = CountVectorizer(lowercase=False)

bag_of_words = vetorizar.fit_transform(dados.avaliacao)
print(bag_of_words.shape)

(15501, 23352)

In [29]:
# Otimizando o código para limitar a quantidade de features geradas pela vetorização


vetorizar = CountVectorizer(lowercase=False, max_features=50)

bag_of_words = vetorizar.fit_transform(dados.avaliacao)
print(bag_of_words.shape)

# A limitação de features considera as palavras que tem maior ocorrencia dentro da dos dados

(15501, 50)

In [33]:
matriz_esparsa_avaliacoes = pd.DataFrame.sparse.from_spmatrix(bag_of_words, columns= vetorizar.get_feature_names_out())
matriz_esparsa_avaliacoes

,Não,Produto,ainda,antes,as,até,bem,bom,chegou,com,...,qualidade,que,recebi,recomendo,se,sem,tem,um,uma,veio
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,1,2,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
15497,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
15498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
15499,0,1,0,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
15500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Separação em treino teste split
from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(bag_of_words, dados.sentimento, random_state=4978)

In [ ]:
# Aplicando algorítmo de Regressão Logística 
from sklearn.linear_model import LogisticRegression

regresssao_logistica = LogisticRegression()
regresssao_logistica.fit(x_treino, y_treino)
acuracia = regresssao_logistica.score(x_teste, y_teste)
acuracia

0.7982456140350878

- Crie uma função chamada classificar_texto, que aceite três parâmetros: o nome do DataFrame, o nome da coluna contendo as avaliações de texto e o nome da coluna correspondente aos sentimentos;
- Utilize a classe CountVectorizer para transformar o texto em um vetor bag of words, com um número máximo de 50 features;
- Separe os dados em conjuntos de treino e teste utilizando train_test_split;
- Crie um modelo de regressão logística e ajuste-o aos dados de treino;
- Calcule e retorne a acurácia do modelo para os dados de teste;
- Retorne o valor da acurácia.

In [67]:
def classificar_testo(df,col_ava_texto, sentimento):
    
    from sklearn.feature_extraction.text import CountVectorizer
    
    vetorizar = CountVectorizer(lowercase=False, max_features=50)

    bag_of_words = vetorizar.fit_transform(df[col_ava_texto])
    print(bag_of_words.shape)

    from sklearn.model_selection import train_test_split

    x_treino, x_teste, y_treino, y_teste = train_test_split(bag_of_words, dados[sentimento], random_state=4978)
    
    from sklearn.linear_model import LogisticRegression

    regresssao_logistica = LogisticRegression()
    regresssao_logistica.fit(x_treino, y_treino)
    acuracia = regresssao_logistica.score(x_teste, y_teste)
   
    return print(f"\nAcurácia do modelo com a coluna '{col_ava_texto}': {acuracia * 100:.2f}%")

In [68]:
classificar_testo(dados,'avaliacao','sentimento')

(15501, 50)

Acurácia do modelo com a coluna 'avaliacao': 79.82%

#### Resumo até aqui

- Explorar dados textuais;
- Utilizar a técnica de Bag of words para converter textos em vetores numéricos;
- Separar os dados em treino e teste;
- Treinar o modelo de regressão logística;
- Obter a acurácia do modelo nos dados de teste.